# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

#options
  nacc_allow_non_json: 'yes'  #disables forced-filtering for json-only requests  (yes/no)

  development:
    #Sessions
    session_duration: '1'

    #mailers
    nacc_mail_address:          'smtp.gmail.com'
    nacc_mail_port:             '587'
    nacc_mail_domain:           'neurral.com'
    nacc_mail_user_name:        'john70xdoe@gmail.com'
    nacc_mail_password:         'mymynd1255'
    nacc_mail_authentication:   'plain'

